[package]
name = "example"
version = "0.1.0"
authors = ["Antoine <antoine.detante@intech.lu>"]
edition = "2018"

[dependencies]
deconz-sp = { path = "../deconz-sp" }
env_logger = "0.6"
tokio = "0.1"
futures = "0.1"