[package]
name = "deconz-sp"
version = "0.1.0"
authors = ["Antoine <antoine.detante@intech.lu>"]
edition = "2018"

[dependencies]
log = "0.4"
failure = "0.1"
serial-line-ip = "0.4"
byteorder = "1.3"
futures = "0.1"
tokio = "0.1"
tokio-serial = "3.2"
mio-serial = "3.2"
bytes = "0.4"
